application: youtube-english-1118
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/html/index.htm
  upload: static/html/index.htm

- url: /hello
  script: _go_app
    
