application: youtube-english-1118
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/html/index.htm
  upload: static/html/index.htm

- url: /hello
  script: _go_app

- url: /db/insert
  script: _go_app

- url: /db/select
  script: _go_app

- url: /ui.js
  static_files: static/html/ui.js
  upload: static/html/ui.js

- url: /js
  static_dir: static/html/js

- url: /css
  static_dir: static/html/css
